version: '3.8'

services:
  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_PASSWORD=1234
  #   ports: 
  #     - "5432:5432"
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data/
     
  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/postgres 
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app 

